<Project>
  <PropertyGroup>
    <Configurations>Debug;Release;Release_CSharp_14</Configurations>
    <Platforms>AnyCPU</Platforms>
  </PropertyGroup>

  <PropertyGroup Condition=" '$(Configuration)' == 'Release_CSharp_14' ">
    <Optimize Condition=" '$(Optimize)' == '' ">true</Optimize>
    <DefineConstants>$(DefineConstants);CSHARP_14</DefineConstants>
    <LangVersion>14</LangVersion>
  </PropertyGroup>

  <PropertyGroup Condition=" '$(Configuration)' != 'Release_CSharp_14' ">
    <LangVersion>12</LangVersion>
  </PropertyGroup>

  <PropertyGroup>
    <TargetFrameworks>net8.0;net10.0;net472</TargetFrameworks>
    <IsPackable>false</IsPackable>
    <SignAssembly>true</SignAssembly>
    <AssemblyOriginatorKeyFile>..\..\MongoDB.Driver.snk</AssemblyOriginatorKeyFile>
  </PropertyGroup>

  <PropertyGroup>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Version)'==''">
    <Version>0.0.0-local</Version>
  </PropertyGroup>

  <PropertyGroup>
    <Company>MongoDB Inc.</Company>
    <Copyright>Copyright © 2010-present MongoDB Inc.</Copyright>
  </PropertyGroup>

  <PropertyGroup>
    <DefineConstants>$(DefineConstants);TRACE</DefineConstants>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FluentAssertions" Version="4.12.0" />
    <PackageReference Include="Microsoft.CodeAnalysis.FxCopAnalyzers" Version="2.6.2" />
    <PackageReference Include="Microsoft.NETFramework.ReferenceAssemblies" PrivateAssets="All" Version="1.0.0" />
    <PackageReference Include="Moq" Version="4.9.0" />
    <PackageReference Include="xunit.v3.mtp-v2" Version="3.2.2" Condition="'$(IsTestProject)' != 'false'" />
    <PackageReference Include="xunit.v3.extensibility.core" Version="3.2.2" Condition="'$(IsTestProject)' == 'false'" />
    <PackageReference Include="xunit.v3.assert" Version="3.2.2" Condition="'$(IsTestProject)' == 'false'" />
    <PackageReference Include="JunitXml.TestLogger" Version="8.0.0" />
    <PackageReference Include="Xunit.Combinatorial" Version="2.0.24" />
  </ItemGroup>

</Project>
