<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsOSX Condition="$([MSBuild]::IsOSPlatform('OSX'))">true</IsOSX>
  </PropertyGroup>

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFrameworks>net472;net8.0;net10.0</TargetFrameworks>
    <LangVersion>9</LangVersion>
    <CodeAnalysisRuleSet>..\..\..\MongoDBTest.ruleset</CodeAnalysisRuleSet>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MongoDB.Driver" Version="$(DRIVER_PACKAGE_VERSION)" Condition="'$(DRIVER_PACKAGE_VERSION)' != ''" />
    <PackageReference Include="MongoDB.Driver.Encryption" Version="$(DRIVER_PACKAGE_VERSION)" Condition="'$(DRIVER_PACKAGE_VERSION)' != ''" />
    <ProjectReference Include="..\..\..\src\MongoDB.Driver\MongoDB.Driver.csproj" Condition="'$(DRIVER_PACKAGE_VERSION)' == ''" />
    <ProjectReference Include="..\..\..\src\MongoDB.Driver.Encryption\MongoDB.Driver.Encryption.csproj" Condition="'$(DRIVER_PACKAGE_VERSION)' == ''" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FluentAssertions" Version="4.12.0" />
    <PackageReference Include="Microsoft.CodeAnalysis.FxCopAnalyzers" Version="2.6.2" />
    <PackageReference Include="xunit.v3.mtp-v2" Version="3.2.2" />
    <PackageReference Include="JunitXml.TestLogger" Version="8.0.0" />
  </ItemGroup>

  <ItemGroup Condition="'$(TargetFramework)' == 'net472'">
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="2.2.0" />
    <PackageReference Include="Microsoft.Extensions.Logging" Version="2.2.0" />
    <PackageReference Include="Microsoft.Extensions.Logging.Configuration" Version="2.2.0" />
    <PackageReference Include="Microsoft.Extensions.Logging.TraceSource" Version="2.2.0" />
  </ItemGroup>

  <ItemGroup Condition="'$(TargetFramework)' == 'net8.0'">
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="8.0.0" />
    <PackageReference Include="Microsoft.Extensions.Logging" Version="8.0.0" />
    <PackageReference Include="Microsoft.Extensions.Logging.Configuration" Version="8.0.0" />
    <PackageReference Include="Microsoft.Extensions.Logging.TraceSource" Version="8.0.0" />
  </ItemGroup>

  <ItemGroup Condition="'$(TargetFramework)' == 'net10.0'">
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.0" />
    <PackageReference Include="Microsoft.Extensions.Logging" Version="10.0.0" />
    <PackageReference Include="Microsoft.Extensions.Logging.Configuration" Version="10.0.0" />
    <PackageReference Include="Microsoft.Extensions.Logging.TraceSource" Version="10.0.0" />
  </ItemGroup>

  <ItemGroup>
    <None Update="xunit.runner.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
